### ISSUE TITLE
Socket.DualMode throws System.PlatformNotSupportedException on the Mac OS

### ISSUE THREAD

**Issue by spaceneb** [tom-weiland/RiptideNetworking#25] opened 2022-02-12 21:20 UTC
Hey, I tried to run some code on the Mac OS and it's giving me the aforementioned exception.
```
Unhandled exception. System.PlatformNotSupportedException: This platform does not support packet information for dual-mode sockets.  If packet information is not required, use Socket.Receive.  If packet information is required set Socket.DualMode to false.
   at System.Net.Sockets.SocketPal.CheckDualModeReceiveSupport(Socket socket)
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at RiptideNetworking.Transports.RudpTransport.RudpListener.Receive()
   at System.Threading.Thread.StartCallback()
   ```
   
   Is it just not compatible with the Mac OS? How trivial would it be to disable DualMode?

**Comment by tom-weiland** [comment] 2022-05-12 03:16
Sorry for the late response—what code exactly are you running that's causing it? Does it happen for both server and client? I'll try to reproduce the problem at some point, but extra info would be helpful.

**Comment by tom-weiland** [comment] 2022-09-07 23:21
@spaceneb if you (or anyone else for that matter) can't provide any extra information about this issue, I'm going to have to close it due to inactivity as it's simply not something I can fix with the current level of information.

I've tried running both a server and a client (the ones from the [dedicated server demo](https://github.com/tom-weiland/RiptideNetworking/tree/main/Demos/Unity/DedicatedServerDemo)) on my MacBook, and it worked completely fine. I can run them and connect them as expected, with no exceptions or other errors popping up.

It's possible that the problem is specific to a certain version of MacOS, so the only way any progress can be made on this is if you let me know what kind of Mac you're using, what version of MacOS it's running, and what you're actually doing when you encounter this error (are you running a client? A server? Both? Etc.).

I also did some searching on the internet and was unable to find anything at all about dual-mode sockets not being supported on MacOS, so I literally have no other leads to help solve this problem.

**Comment by tom-weiland** [comment] 2022-09-09 23:46
I'm still unable to reproduce this issue, but I've now added an option to disable dual-mode sockets and instead use either only IPv4 or only IPv6 (see commits ddc3c4a0b45d265bb40906ba9770d00cbbcc8108 and ffb308f70c5ce53caaa9f2fcaf97f1378bb23d3c). The change will be part of v2.0.0 so I'm going to close this issue for now.

**Closed by tom-weiland** 2022-09-09 23:46 UTC
Labels: Bug, More Info Required, MacOS

**Comment by Loch9** [comment] 2022-11-06 13:25
I also get this issue on Mac.
MacOS High Sierra (10.13.6), [this git repo has produces the problem on my machine](https://github.com/Loch9/ChatApp).

**Comment by vrmaurice** [comment] 2023-11-24 00:17
I've got the same issue, my Mac is MacBook Air M2. Running macOS Sonoma.

This is my server code.

`using Riptide;

public class NetworkManager
{
    private Server _server;

    private ushort _port;
    private ushort _maxClients;

    public NetworkManager(ushort port, ushort maxClients)
    {
        _server = new Server();

        _port = port;
        _maxClients = maxClients;
    }

    public void Start()
    {
        _server.Start(_port, _maxClients);

        Thread updateThread = new Thread(UpdateServer);
        updateThread.Start();
    }

    private void UpdateServer()
    {
        while (true)
        {
            _server.Update();
        }
    }
}`

**Comment by tom-weiland** [comment] 2023-11-24 01:00
> I've got the same issue, my Mac is MacBook Air M2. Running macOS Sonoma.

Did you read [this comment](https://github.com/RiptideNetworking/Riptide/issues/25#issuecomment-1242561517) of mine? It doesn't look like you've disabled dual-mode...

**Comment by vrmaurice** [comment] 2023-11-24 14:33
It's not clear to me where exactly I need to disable it in Riptide.

**Comment by tom-weiland** [comment] 2023-11-24 19:39
Replace 
```cs
_server = new Server();
```
with
```cs
_server = new Server(new UdpServer(SocketMode.IPv4Only));
```
And do the same for the client (but obviously with `UdpClient` instead of `UdpServer`).
