### ISSUE TITLE
Multiple TCP clients go offline quickly, which will lead to errors.

### ISSUE THREAD

**Issue by 664028812** [tom-weiland/RiptideNetworking#37] opened 2022-04-26 01:56 UTC
Multiple TCP clients go offline quickly, which will lead to errors.  
eg：  
I don't think it's reasonable to deal with it here
        private void Heartbeat()
        {
            lock (clients)
            {
                foreach (RudpConnection client in clients.Values)
                    if (client.HasTimedOut)
                        timedOutClients.Add(client.RemoteEndPoint);
            }

            foreach (IPEndPoint clientEndPoint in timedOutClients)
                HandleDisconnect(clientEndPoint); // Disconnect the clients

            timedOutClients.Clear();
        }

**Comment by 664028812** [comment] 2022-04-26 02:00
at System.Collections.Generic.List1.Enumerator.MoveNextRare()    at RiptideNetworking.Transports.RudpTransport.RudpServer.Heartbeat()    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown ---    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)    at System.Threading.TimerQueue.FireNextTimers() System.InvalidOperationException: Collection was modified; enumeration operation may not execute.    at System.Collections.Generic.List1.Enumerator.MoveNextRare()
at RiptideNetworking.Transports.RudpTransport.RudpServer.Heartbeat()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
at System.Threading.TimerQueue.FireNextTimers()
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List1.Enumerator.MoveNextRare()    at RiptideNetworking.Transports.RudpTransport.RudpServer.Heartbeat()    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown ---    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)    at System.Threading.TimerQueue.FireNextTimers() System.InvalidOperationException: Collection was modified; enumeration operation may not execute.    at System.Collections.Generic.List1.Enumerator.MoveNextRare()
at RiptideNetworking.Transports.RudpTransport.RudpServer.Heartbeat()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
at System.Threading.TimerQueue.FireNextTimers()

**Comment by tom-weiland** [comment] 2022-04-26 03:07
> I don't think it's reasonable to deal with it here

Alright, but what exactly makes you think that? Do you have steps to reproduce this issue consistently, ideally using one of the demo projects?

> TCP clients

Just to clarify, Riptide doesn't use TCP at all.

**Comment by tom-weiland** [comment] 2022-07-02 03:43
Closing this due to a lack of information, clarification, and any response from @664028812.

**Closed by tom-weiland** 2022-07-02 03:43 UTC
Labels: Bug, More Info Required
