### ISSUE TITLE
Only one usage of each socket address (protocol/network address/port) is normally permitted ERROR

### ISSUE THREAD

**Issue by islaitala** [tom-weiland/RiptideNetworking#53] opened 2022-06-29 22:00 UTC
How I get this error, having server software in editor and restarting the server many times. I am using 2021.3.0f1

**Comment by tom-weiland** [comment] 2022-06-30 01:26
Unless you can find a way to reproduce it consistently, there's not much I'll be able to do to fix it.

A few others have mentioned this happening, and reopening the project always fixes it—apparently the editor is keeping the socket in use somehow or something, despite the `Server.Stop` and `Client.Disconnect` methods closing it when called, so it may actually be a Unity bug and not a problem with Riptide.

**Comment by tom-weiland** [comment] 2022-07-07 06:00
@islaitala I've just overhauled Riptide's transport system, which included removing the multi-threaded code and it seems to have fixed a similar issue which occurred under certain circumstances in the player-hosted demo.

I haven't merged these changes into the main branch yet, but you can get them by grabbing the dll from one of the demos off the `transport-rework` branch, or by installing the package from Unity's package manager using this URL: `https://github.com/tom-weiland/RiptideNetworking.git?path=/Unity/Packages/Core#transport-rework`

If possible, could you check if this is still an issue for you with the new changes? Just be aware that I've renamed a lot of things since v1.2.0, so you may have to fix some errors when you update.

**Comment by tom-weiland** [comment] 2022-07-12 05:43
Going to close this for now as it's quite likely that it's a Unity problem, especially after PR #56 which removed Riptide's multi-threading, thereby resolving any threading-related occurrences of this error.

If anyone runs into this again and has reason to believe that it's *not* Unity's fault, please let me know and we can re-open the issue.

**Closed by tom-weiland** 2022-07-12 05:43 UTC
Labels: More Info Required
